pipeline {
    agent any

    stages {
        stage('Pull') {
            steps {
                echo 'Pulling code...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing Terraform...'
            }
        }

        stage('Approval') {
            steps {
                echo 'Waiting for approval...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
# trigger pipeline